#!/bin/bash
PASSED=0
TOTAL=0
SECONDS=0

pip install -e .

tests=( "tests/test_e3sm.py"
        "tests/test_aprime.py"
        "tests/test_amwg.py"
        "tests/test_climo.py"
        "tests/test_filemanager.py"
        "tests/test_initialize.py"
        "tests/test_mailer.py"
        "tests/test_slurm.py"
        "tests/test_finalize.py"
        "tests/test_runmanager.py"
        "tests/test_timeseries.py"
        "tests/test_util.py"
        "tests/test_verify_config.py"
        #"tests/test_processflow.py"
        )

if [ "$1" == "all" ]; then
    echo "Running end to end tests"
    tests+=("tests/test_processflow_run.py")
    tests+=("tests/test_transfer.py")
elif [ "$1" == "globus" ]; then
    tests+=("tests/test_transfer.py")
    echo "Running with Globus transfer tests"
elif [ "$1" == "processflow_only" ]; then
    tests=("tests/test_processflow_run.py")
    echo "Only running end to end tests"
else
    echo "Skipping end to end and file transfer tests"
fi

for test in "${tests[@]}" 
do
    if [ -d test.db ]; then
        rm test.db
    fi
    (( TOTAL+=1 ))
    tname=$(python -c "name='${test}';tname=name.split('/')[-1].split('.')[0];print tname")
    echo "--- running ${tname} ---"
    if COVERAGE_FILE=.coverage_$tname coverage run --source=processflow --omit="processflow/resources/*","tests/test_*","*__init__.py","setup.py" $test; then
        echo "--- ${tname} passed ---"
        (( PASSED+=1 ))
    else
        echo "==================================================="
        echo "==================================================="
        echo "${tname} failed"
        echo "==================================================="
        echo "==================================================="
    fi
done

coverage combine .coverage_*
coverage report
coverage html
coverage xml

echo $PASSED "out of" $TOTAL "modules passed their tests"
duration=$SECONDS
echo "Tests ran in $(($duration / 60)) minutes and $(($duration % 60)) seconds."

if [ "$PASSED" != "$TOTAL" ]; then
    echo "One or more tests failed"
    exit 1
else
    if [ -d /var/www/acme/acme-diags/baldwin32/htmlcov ]; then
        rm -rf /var/www/acme/acme-diags/baldwin32/htmlcov
    fi
    mv htmlcov /var/www/acme/acme-diags/baldwin32
    echo "tests done"
    echo "report available at https://acme-viewer.llnl.gov/baldwin32/htmlcov/"
fi
