#!/bin/bash

# LOAD THE MACHINE-SPECIFIC ANACONDA-2.7 ENVIRONMENT
echo "Loading e3sm-unified environment"
source $MODULESHOME/init/bash
if [ ${HOSTNAME:0:6} == "edison" ]; then
  export machname="edison"
elif [ ${HOSTNAME:0:4} == "cori" ]; then
  export machname="cori"
elif [ ${HOSTNAME:0:4} == "rhea" ]; then
  export machname="rhea"
elif [ ${HOSTNAME:0:5} == "titan" ]; then
  export machname="titan"
elif [ ${HOSTNAME:0:5} == "aims4" ]; then
  export machname="aims4"
elif [ ${HOSTNAME:0:5} == "acme1" ]; then
  export machname="acme1"
elif [ ${HOSTNAME:0:4} == "wolf" ] || [ ${HOSTNAME:0:7} == "grizzly" ]; then
  export machname="lanl"
elif [ ${HOSTNAME:0:6} == "blogin" ] || ([ ${HOSTNAME:0:1} == "b" ] && [[ ${HOSTNAME:1:2} =~ [0-9] ]]); then
  export machname="anvil"
elif [ ${HOSTNAME:0:6} == "cooley" ] || ([ ${HOSTNAME:0:2} == "cc" ] && [[ ${HOSTNAME:2:3} =~ [0-9] ]]); then
  export machname="cooley"
else
  echo "Unsupported host $HOSTNAME. Exiting."
  exit 1
fi

if [ $machname == "edison" ]; then
  module unload python
  module unload python_base
  source /global/project/projectdirs/acme/software/anaconda_envs/edison/base/etc/profile.d/conda.sh
  conda activate e3sm_unified_1.2.0_py2.7_nox
  export NCO_PATH_OVERRIDE=No
elif [ $machname == "cori" ]; then
  module unload python
  module unload python_base
  source /global/project/projectdirs/acme/software/anaconda_envs/cori/base/etc/profile.d/conda.sh
  conda activate e3sm_unified_1.2.0_py2.7_nox
  export NCO_PATH_OVERRIDE=No
elif [ $machname == "rhea" ] || [ $machname == "titan" ]; then
  module unload python
  source /ccs/proj/cli900/sw/rhea/e3sm-unified/base/etc/profile.d/conda.sh
  conda activate e3sm_unified_1.2.0_py2.7_nox
  export NCO_PATH_OVERRIDE=No
elif [ $machname == "acme1" ]; then
  source /usr/local/e3sm_unified/envs/base/etc/profile.d/conda.sh
  conda activate e3sm_unified_1.2.0_py2.7_nox
  export NCO_PATH_OVERRIDE=No
elif [ $machname == "aims4" ]; then
  source /usr/local/e3sm_unified/envs/base/etc/profile.d/conda.sh
  conda activate e3sm_unified_1.2.0_py2.7_nox
  export NCO_PATH_OVERRIDE=No
elif [ $machname == "lanl" ]; then
  module unload python
  source /usr/projects/climate/SHARED_CLIMATE/anaconda_envs/base/etc/profile.d/conda.sh
  conda activate e3sm_unified_1.2.0_py2.7_nox
elif [ $machname == "anvil" ]; then
  source /lcrc/soft/climate/e3sm-unified/base/etc/profile.d/conda.sh
  conda activate e3sm_unified_1.2.0_py2.7_nox
  unset LD_LIBRARY_PATH
elif [ $machname == "cooley" ]; then
  source /lus/theta-fs0/projects/ClimateEnergy_2/software/e3sm_unified/base/etc/profile.d/conda.sh
  conda activate e3sm_unified_1.2.0_py2.7_nox
fi

acme_diags_driver.py -p {{ parameter_file_path }}
